# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
#  push:
#    branches: [ main ]
#    paths:  
#      - '!subfolder1/**'
#      - 'subfolder1/subfolder2/subfolder3/project/**'
  pull_request:
    branches: [ main ]
    paths:  
      - '!subfolder1/**'
      - 'subfolder1/subfolder2/subfolder3/project/**'

defaults:
  run:
    working-directory:  './subfolder1/subfolder2/subfolder3/project'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache node modules
      id: projectCacheStep
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
          
    - name: Install dependencies
      # if: steps.projectCacheStep.outputs.cache-hit != 'true'
      # run: npm install
      run: npm ci
      
    # - run: npm ci
    - run: npm run build --if-present
    - run: npm test
